-- MySQL Script generated by MySQL Workbench
-- Tue Aug  3 11:32:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Groupomania
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Groupomania
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Groupomania` DEFAULT CHARACTER SET utf8 ;
USE `Groupomania` ;

-- -----------------------------------------------------
-- Table `Groupomania`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Groupomania`.`Users` (
  `idUsers` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `Groupomania`.`Users` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Groupomania`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Groupomania`.`Posts` (
  `idPosts` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `dateCreation` DATETIME NOT NULL,
  `message` LONGTEXT NOT NULL,
  `media` VARCHAR(255) NULL,
  `userId` INT UNSIGNED NULL,
  PRIMARY KEY (`idPosts`),
  CONSTRAINT `Fk_posts_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `Groupomania`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Fk_posts_userId_idx` ON `Groupomania`.`Posts` (`userId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Groupomania`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Groupomania`.`Comments` (
  `idComments` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message` LONGTEXT NOT NULL,
  `dateCreation` DATETIME NOT NULL,
  `userId` INT UNSIGNED NULL,
  `postId` INT UNSIGNED NULL,
  PRIMARY KEY (`idComments`),
  CONSTRAINT `Fk_comments_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `Groupomania`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_comments_postId`
    FOREIGN KEY (`postId`)
    REFERENCES `Groupomania`.`Posts` (`idPosts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Fk_comments_userId_idx` ON `Groupomania`.`Comments` (`userId` ASC) VISIBLE;

CREATE INDEX `Fk_comments_postId_idx` ON `Groupomania`.`Comments` (`postId` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
